### ISSUE TITLE
Delete multidev environments as soon as PR is merged

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/terminus-build-tools-plugin#1]
Currently, multidev environments created to test pull requests are not deleted until the GitHub branch for the PR is deleted. It would be desirable for this deletion to happen if the PR is closed or merged, even if the user does not remember to delete the branch.

There are several ways this could be done.

1. Use the GitHub API:

A list of all PRs can be obtained via the [list pull request](https://developer.github.com/v3/pulls/#list-pull-requests) API. The result contains a "head" element that contains "label" and "ref" elements which should contain the appropriate branch name. The pull request list can be limited to only the open PRs; ergo, if a given multidev branch cannot be found in any open pull request, it can be presumed that the PR is merged or closed.

2. Record the PR in the commit containing the build artifacts

CircleCI provides the pull request number via the CIRCLE_PR_NUMBER environment variable. This value could be passed in to the `build-env:create` command. For pull requests, the first build will always create a new branch, and the build artifacts will be committed to it. The PR number could be written into the commit comment, which would be useful vis-a-vis documentation in any event. What is really needed, though, is the `CIRCLE_BRANCH`, which could also be written into the commit comment, but it wouldn't scan as well. To recover the branch, we would have to get the commit comments `terminus env:code-log <site>.<env>`. This option would probably be a lot slower than the first option.

**Comment by greg-1-anderson** [comment]
This is working now.

**Comment by brooke-heaton** [comment]
@greg-1-anderson What do I need to do to get this working on my build?
