### ISSUE TITLE
build:env:delete:ci fails with BitBucket

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#109]
`build:env:delete:ci` attempts to call out to the GitHub API even though the site is in BitBucket.

`build:env:delete:ci` should accept a `--ci` flag to specify BitBucket

**Comment by awolfey** [comment]
I'm able to help test if there's any progress on this. Thanks.

**Comment by aaronbauman** [comment]
This appears to be fixed in master, but the circle script is still pegged to ^1 / [1.3.9](https://github.com/pantheon-systems/terminus-build-tools-plugin/releases/tag/1.3.9) from last July

I updated the circle.yml to checkout dev-master, and now i'm running into the issue in #120

**Comment by ataylorme** [comment]
Closing as a duplicate to #145 for proper BitBucket support
