### ISSUE TITLE
Can CircleCI be updated to Drush 9?

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/terminus-build-tools-plugin#112]
On my local dev environment I updated to Drupal 8.4.0, Commerce 2, and Drush 9.

However, now my CircleCI builds break:

**Example 1**

```
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y
Warning: Permanently added '[appserver.pr-kaizen.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in]:2222,[35.184.135.158]:2222' (RSA) to the list of known hosts.

PHP Fatal error:  Call to undefined function drupal_get_installed_schema_version() in /srv/bindings/890147b39cde4b2eaca8e463e3553346/code/web/core/includes/install.inc on line 80
 [error]  Drush command terminated abnormally due to an unrecoverable error.
Error: Call to undefined function drupal_get_installed_schema_version() in /srv/bindings/890147b39cde4b2eaca8e463e3553346/code/web/core/includes/install.inc, line 80 
 [notice] Command: edosensei.pr-kaizen -- drush updatedb [Exit: 255]
 [error]   
```

**Example 2**

```
terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
Warning: Permanently added '[appserver.pr-kaizen.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in]:2222,[35.184.135.158]:2222' (RSA) to the list of known hosts.

 [error]  The Drush command 'config-import' could not be found. Use 'drush core-status' to verify that Drupal is found and bootstrapped successfully. Look for 'Drupal bootstrap : Successful' in its output. 
 [warning] DateTime::createFromFormat(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. Response.php:231
```

So then I tried changing `/usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer -n --working-dir=$HOME require drush/drush "^8"` to `^9` but this causes the build to fail almost immediately:

```
  Problem 1
    - The requested package drush/drush ^9 is satisfiable by drush/drush[9.0.0-alpha1, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-beta4, 9.0.0-beta5, 9.0.x-dev] but these conflict with your requirements or minimum-stability.

```

Specifying `9.0.0-beta5` doesn't help either:

```
/usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer -n --working-dir=$HOME require drush/drush "9.0.0-beta5"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drush/drush 9.0.0-beta5 -> satisfiable by drush/drush[9.0.0-beta5].
    - drush/drush 9.0.0-beta5 requires consolidation/annotated-command dev-master as 2.7.0 -> satisfiable by consolidation/annotated-command[dev-master] but these conflict with your requirements or minimum-stability.
```

Am I correct in assuming upgrading the drush in my repo to version 9 is the problem here, and if so, how can I fix it?

**Comment by greg-1-anderson** [comment]
There are several problems here:

- Drush 8.x does not work as a site-local Drush with Drupal 8.4.0 and later.
- Drush 9.0.0-beta4 and earlier are deprecated, and cannot be relied on.
- Drush 9.0.0-beta5 was released with dev dependencies (as you show above).

Drush 9.0.0-beta6 will be tagged shortly. Please try again and sync up back here with your results.

In the meantime, you could try removing Drush from your project, and use a global install of Drush 8.1.14 or 9.0.0-beta5.

**Comment by ptmkenny** [comment]
Thank you for the detailed explanation of what the issue is here.

I tried updating to `Drush 9.0.0-beta6` and got the following error:
```

/usr/bin/env COMPOSER_BIN_DIR=$HOME/bin composer -n --working-dir=$HOME require drush/drush "9.0.0-beta6"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drush/drush 9.0.0-beta6 -> satisfiable by drush/drush[9.0.0-beta6].
    - Conclusion: remove phpdocumentor/reflection-docblock 4.1.1
    - Conclusion: don't install phpdocumentor/reflection-docblock 4.1.1
    - drush/drush 9.0.0-beta6 requires phpdocumentor/reflection-docblock ^2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.0, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.1, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.2, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.3, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.4, 4.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[2.0.5, 4.1.1].
    - Installation request for phpdocumentor/reflection-docblock (locked at 4.1.1) -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].


Installation failed, reverting ./composer.json to its original content.
```

I get the same error when trying to update to `beta4` (I know you said it was deprecated, but I figured it was worth a try).

The suggested workaround (removing drush from the project) does allow the builds to complete on CircleCI, so that's a big help.

**Comment by greg-1-anderson** [comment]
Looks like you have an older version of the test scripts.  `--working-dir=$HOME` is a bug. This was fixed to `--working-dir=$HOME/drush` (mkdir $HOME/drush first). The latest version of the example project does not do this at all -- now, the tools are pre-installed in a Docker container.

The version you are using is trying to install both Terminus and Drush (and maybe other things) directly into $HOME, which is why you are getting requirements conflicts.

**Comment by greg-1-anderson** [comment]
You could leave the Drush version installed in circle.yml at 8.x, and change the require in your composer.json to 9.x.

**Comment by greg-1-anderson** [comment]
I ran `composer require drush/drush:^9` in the root of my example-drops-8-composer project, and it worked. Didn't try to run tests on it, but the `composer require` command worked, anyway.

**Comment by ptmkenny** [comment]
Leaving the circle.yml drush at 8 and installing Drush 9 with composer works for local development, but it breaks when I push changes up to github and they get sent to CircleCI.  This was actually the problem that caused me to post this issue; you can see the errors in the first two examples in the top post.

That said, if my build scripts are older, I would be happy to update them.  I installed the build tools according to the Pantheon documentation, but the section on "Updates" only talks about using composer to update, not how to update the build tools themselves:
https://pantheon.io/docs/guides/build-tools/update/

What would be your recommendation for updating the build tools scripts?

**Comment by greg-1-anderson** [comment]
You'd need to fork https://github.com/pantheon-systems/docker-build-tools-ci

**Comment by greg-1-anderson** [comment]
Maybe we could make a branch on that repository for Drush 9.

**Comment by ptmkenny** [comment]
Yes, it would be great to have a Drupal 8.4/Drush 9 example.

Also, for reference, I just built a new repo following the build tools documentation (https://pantheon.io/docs/guides/build-tools/update/) and I still got the old script (` --working-dir=$HOME require drush/drush "^8"`).

**Comment by greg-1-anderson** [comment]
Note also that Drush 9 does not currently work on the platform. That should be fixed shortly.

**Comment by greg-1-anderson** [comment]
Drush 9 works on Pantheon as a site-local dependency now.

**Comment by ataylorme** [comment]
Cleaning up old issues. This should be addressed in `example-drops-8-composer` but that won't happen until Drush 9 is the default on Pantheon
