### ISSUE TITLE
build:project:create does not put correct CI badge in README

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/terminus-build-tools-plugin#116]
The initial [ci | none] badge persists -- the Circle CI badge is not inserted.

**Comment by ataylorme** [comment]
Unknown if this still occurs

**Comment by greg-1-anderson** [comment]
Presently the badge is being updated, but its contents is not correct.

Badge points to https://gitlab.com/_namespace_/_project_. Should point to https://gitlab.com/_namespace_/_project_/pipelines.

Badge graphic should be:

https://example.gitlab.com/_namespace_/_project_/badges/_branch_/pipeline.svg

I'll fix this.
