### ISSUE TITLE
Bitbucket fails on CircleCI

### ISSUE THREAD

**Issue by yoxalld** [pantheon-systems/terminus-build-tools-plugin#120]
[error]  Client error: `GET https://api.bitbucket.org/2.0/repositories/CakeAndEatItDesigns/cake-eat-it-bitbucket-test/pullrequests?state=MERGED&state=DECLINED&state=SUPERSEDED` resulted in a `401 Unauthorized` response

**Comment by greg-1-anderson** [comment]
The BitBucket integration is not fully working. We may not be able to support a smooth startup of these two services together. My understanding is that you have to authenticate Circle for the new project once using a web browser, and thereafter the CI works.

**Comment by aaronbauman** [comment]
I'll hop on this existing thread, but maybe this is a new issue. I'm getting a different error during project:create:

` [notice] Call CircleCI API: https://circleci.com/api/v1.1/project/bitbucket/messageagency/tmp20180124-2/envvar
 [CompletionWrapper]  Server error: `POST https://circleci.com/api/v1.1/project/bitbucket/messageagency/tmp20180124-2/envvar` resulted in a `500 Internal Server Error` response:

<html>
  <head>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', "UA-25 (truncated...)
 
 [CompletionWrapper]  Exit code 500 
 19/19 [============================] 100%  1 sec/1 sec  10.0 MiB
 [error]   
`

Creating the bitbucket project is successful, so I know my environment creds are good. Also I've added Circle as an OAuth client to my bitbucket.

Do I need to create the circle project first?

**Comment by ataylorme** [comment]
Closing as a duplicate of #145 requesting proper BitBucket support
