### ISSUE TITLE
Set TERMINUS_HIDE_UPDATE_MESSAGE environment variable

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#121]
Projects created with the build tools plugin will fail when the Terminus version from our Docker container isn't the latest as the Terminus update notice causes build failure in strict mode.

We should set the `TERMINUS_HIDE_UPDATE_MESSAGE` environment variable on new projects so this does not happen.

**Comment by ari-gold** [comment]
@ataylorme I can't seem to reproduce. I just created a new project and the Circle Build [succeeded](https://circleci.com/gh/ari-gold/ari-d8-build-tools-1/1). Are you still able to reproduce the issue?

**Comment by ataylorme** [comment]
@ari-gold this happened in a training when making a pull request, the initial build was okay. I'll send you the recording of exactly what happened.

**Comment by ataylorme** [comment]
Further investigation showed Terminus update notices weren't the issue causing the failure but it is causing noise in the builds when folks have no power to update the Terminus version in our Docker image. A way to suppress the notice is still desirable but doesn't have as high of a priority.
