### ISSUE TITLE
build:env:delete not working on multi-dev environments

### ISSUE THREAD

**Issue by xpersonas** [pantheon-systems/terminus-build-tools-plugin#125]
`terminus build:env:delete modern-welding '^ci-' --delete-branch`

Running that returns...
`[notice] Nothing to delete. Keeping ci-49,ci-51,ci-54,ci-56.`

Seems this command would delete at least two of those. Am I not using the regex right?

**Comment by aaronbauman** [comment]
i'm having the same issue.
try the fix in #128

**Comment by karens** [comment]
Same problem here. Our pr- environments are deleted, but ci- environment are never deleted. Looked at the linked issue, which includes a fix that was later deleted. I'm not sure that is the right fix but I think it highlights the problem. The base logic seems to request information about PRs from GitHub then look for the ci- pattern in closed PRs to see what PRs to keep. That logic might (apparently) work if you are looking for the pr- pattern, but does not work if you are looking for the ci- pattern.

**Comment by ataylorme** [comment]
#171 resolved this but you will need to update your Terminus Build Tools version. You can use `quay.io/pantheon-public/build-tools-ci:6.x`, which is [the Dockerfile Pantheon maintains](https://github.com/pantheon-systems/docker-build-tools-ci/) that contains Terminus, build tools, and other components
