### ISSUE TITLE
Template project not on Packagist?

### ISSUE THREAD

**Issue by datvance** [pantheon-systems/terminus-build-tools-plugin#126]
Currently, one must publish their custom template project to packagist.org to use it from this plugin. This is problematic if one doesn't want their project to be public. A solution could be to allow passing through the --repository flag to composer create-project...

`terminus build:project:create --repository='{"type": "vcs","url": "https://github.com/ORG/template-project"}' ORG/template-project site-name`

[Doc block for ProjectCreateCommand::createProject](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Commands/ProjectCreateCommand.php#L188) is a bit confusing on this point, suggesting that you can point to a GitHub project:

> * Create a new project from the requested source GitHub project.
> * Does the following operations:
> *  - Creates a git repository forked from the source project.

While in reality you must specify an existing Packagist package.

**Comment by ataylorme** [comment]
I've used `build:project:create` with a GitHub repository not on Packagist successfully. It was a public repository. @datvance are you hoping to use a private repository as a source?

**Comment by datvance** [comment]
Honestly, I don't remember as I posted this issue a year ago, and we're not
using the build-tools-plugin anymore. But yes, I think we did want to use a
private repo as the source.

**Comment by ataylorme** [comment]
> we're not using the build-tools-plugin anymore

I'm going to close this out since you no longer have a need here and others haven't requested this feature
