### ISSUE TITLE
CircleCI build failing with "shallow update not allowed"

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/terminus-build-tools-plugin#129]
I have made about 100 commits and 10 successful pull requests in my repo, which I set up by following the [Build Tools guide](https://pantheon.io/docs/guides/build-tools/).

However, after a month of leaving the site alone, when I came back and pushed from local to GitHub, my CircleCI builds are failing with the message "shallow update not allowed":

```
 [notice] Running git -C /home/ubuntu/myrepo commit -q -m 'Build assets for pr-BRANCH.'
 [notice] Enabled git push mode for "pr-BRANCH"
 [notice] Running git -C /home/ubuntu/myrepo push --force -q pantheon pr-BRANCH
Warning: Permanently added '[codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in]:2222,[35.188.167.131]:2222' (RSA) to the list of known hosts.

remote: 
remote: PANTHEON NOTICE:
remote: 
remote: Changes to `pantheon.yml` detected.
remote: 
remote: Successfully applied `pantheon.yml` to the 'pr-BRANCH' environment.
remote: 
remote: 
To ssh://codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in:2222/~/repository.git
 ! [remote rejected] pr-BRANCH -> pr-BRANCH (shallow update not allowed)
error: failed to push some refs to 'ssh://codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b@codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in:2222/~/repository.git'
 [error]  Command `git -C /home/ubuntu/myrepo push --force -q pantheon pr-BRANCH` failed with exit code 1 

terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --db-only --notify="$NOTIFY" returned exit code 1

Action failed: terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --db-only --notify="$NOTIFY"
```

I thought it might be the changes to the pantheon.yml (changing from PHP 7 to 7.1), but I reverted that commit and I'm still getting the exact same error.

I don't understand enough about git/the build tools to troubleshoot this error.  Is there an easy way to fix this?

**Comment by greg-1-anderson** [comment]
I'm not sure. The operation that is failing is operating against the Pantheon repository. Have you checked on the dashboard to see if the site is frozen?

**Comment by ptmkenny** [comment]
@greg-1-anderson The site is not frozen; it's live right now and I've been making updates to production throughout the day.  However, the push is going to a multidev that I have never touched (except through the build tools workflow).  Could that have something to do with it?

**Comment by greg-1-anderson** [comment]
You could try deleting the PR multidev from the dashboard. You would lose any changes you made to the database, but the next test on the PR would create the multidev again.

**Comment by ptmkenny** [comment]
@greg-1-anderson Ok, I deleted the multidev and then had CircleCI rebuild the environment.  Unfortunately, I'm getting the same error after it re-creates the multidev repo:

```
Warning: Permanently added '[codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in]:2222,[35.188.167.131]:2222' (RSA) to the list of known hosts.

error: Could not read ccc589d07e8d9374399d5b4b767b244aebe42bcf
To ssh://codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in:2222/~/repository.git
 ! [remote rejected] pr-BRANCH -> pr-BRANCH (shallow update not allowed)
error: failed to push some refs to 'ssh://codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b@codeserver.dev.2d533f7c-4fcb-47fd-b446-fe89c364f57b.drush.in:2222/~/repository.git'
 [error]  Command `git -C /home/ubuntu/myrepo push --force -q pantheon pr-BRANCH` failed with exit code 1 

terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --db-only --notify="$NOTIFY" returned exit code 1

Action failed: terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --db-only --notify="$NOTIFY"
```

I also noticed that after deleting the multidev branch in the dashboard and confirming it was gone by refreshing the page, when the branch is "re-created" by CircleCI, it shows up in the dashboard again exactly as it was when it was deleted (Code updated a month ago by Circle CI... 25 commits ahead, 14 behind).

The Pantheon infrastructure alert page notes some kind of problem with repos, so perhaps that is the cause?  I'll try again after the infrastructure alert is closed.

**Comment by greg-1-anderson** [comment]
That could be it. If it does not clear itself up, try deleting the multidev with Terminus, and use the option to delete the branch as well. If it's still broken, open a ticket with support.

**Comment by ptmkenny** [comment]
@greg-1-anderson Unfortunately, in Terminus it just hangs after confirming the delete, so I've opened up a ticket.  I'll update this thread once I get a solution.

**Comment by ptmkenny** [comment]
Pantheon support gave me this fix-- add the following line to circle.yml:
`    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"`

Here's where to put it:
```
  pre:
    - echo "Begin build for $CIRCLE_ENV${PR_ENV:+ for }$PR_ENV. Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"
    - |
      if [ -n "$GITHUB_TOKEN" ] ; then
        composer -n config --global github-oauth.github.com $GITHUB_TOKEN
      fi
    - git config --global user.email "$GIT_EMAIL"
    - git config --global user.name "Circle CI"
    - git config --global core.fileMode false
    - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
```
