### ISSUE TITLE
build:project:create failing at drush site-install

### ISSUE THREAD

**Issue by pcrm-karen** [pantheon-systems/terminus-build-tools-plugin#131]
I have been trying unsuccessfully to get the terminus build:project:create command to work. I'm on Windows 7 and am using the Git BASH emulator with Git for Windows. I worked through several errors, but seem to be stuck on the latest error:

[notice]  - drush site-install standard --account-mail="[REDACTED]" --account-name=admin --account-pass="[REDACTED]" --site-mail="[REDACTED]" --site-name=physicians-committee --yes
[error]  Install site failed with exit code 126

drush is working on the command line in Git BASH. Any ideas?

**Comment by greg-1-anderson** [comment]
Exit code 126 is `Permission problem or command is not an executable`. If Drush is working in other contexts (e.g. `terminus drush`), then I'm not sure what the problem here is.

**Comment by pcrm-karen** [comment]
terminus drush is working. For example, the following terminus drush commands work:

$ terminus drush pcrm-main-site.dev -- en devel --yes
 [notice] Command: pcrm-main-site.dev -- drush en devel [Exit: 0]

$ terminus drush pcrm-main-site.dev -- dis devel --yes
 [notice] Command: pcrm-main-site.dev -- drush dis devel [Exit: 0]

However, I have noticed that no output is returned for the terminus drush commands. For example, the following command seems to work, but no status output is returned:

$ terminus drush pcrm-main-site.dev -- status
 [notice] Command: pcrm-main-site.dev -- drush status [Exit: 0]

The status output is returned if the drush command is used on its own. I found the following terminus bug report that indicates other Windows users are having this issue. Could this be causing the issue with the terminus build:project:create command?

https://github.com/pantheon-systems/terminus/issues/1810

**Comment by greg-1-anderson** [comment]
Possibly. If you run `terminus drush site.env -- site-install --yes ...` (fill in parameters used by the build:project:create) from the command line, does it work (without output) or fail to install?

**Comment by pcrm-karen** [comment]
I created a Pantheon site for testing and ran the following command and it was able to install the new site:

$ terminus drush build-tools-test.dev -- site-install standard --account-mail="[REDACTED]" --account-name=admin --account-pass="[REDACTED]"  --site-mail="[REDACTED]" --site-name=build-tools-test --yes
 [notice] Command: build-tools-test.dev -- drush site-install standard [Exit: 0]

I'm stumped as to why this is working on the command line but isn't working as part of the terminus build:project:create command.

**Comment by dchaffin** [comment]
@pcrm-karen - Have you made any progress on this? I'm experiencing the same issue except I'm not certain my terminus drush is working. If I run:

`drush help`

... locally it works, but:

`terminus drush mysite.dev -- help`

... gives me [Exit: 126].

I too have a site on Pantheon and am trying the command you have above and getting [Exit: 126] there as well.

**Comment by dchaffin** [comment]
@steigenTI - As I understand it, on Git Bash on W10, the [Exit: 0] with no error is a successful completion. I too was able to succesfully follow this walkthrough:

https://pantheon.io/docs/guides/drupal8-commandline/

... but the same (I believe?) commands in the build tools script fail.

**Comment by ataylorme** [comment]
Closing this as Terminus itself does not support Windows therefore this plugin will not support Windows either
