### ISSUE TITLE
Build fails with "[error]  Successfully queued ellis_clone_files"

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/terminus-build-tools-plugin#140]
Haven't seen this error before.

The error did not recur after re-running the build.

**Comment by stevector** [comment]
I also saw this error with a regular `terminus env:create` command on a few CI builds this afternoon too. Fails started here https://circleci.com/gh/pantheon-systems/pantheon_advanced_page_cache/517 and I reran until I got a pass here https://circleci.com/gh/pantheon-systems/pantheon_advanced_page_cache/522

**Comment by dealancer** [comment]
@aaronbauman @stevector is there a way to wait until the task is done?

**Comment by ataylorme** [comment]
@aaronbauman or @dealancer are you still seeing this behavior?

**Comment by aaronbauman** [comment]
Occasionally, yes.
Not able to recreate reliably.

**Comment by ataylorme** [comment]
If your build logs are public do you mind linking a few recent examples of failures?

**Comment by ataylorme** [comment]
I'd also be curious what Terminus version you are using as this seems more like an underlying error with Terminus calling the Pantheon APIs than with build tools.

**Comment by aaronbauman** [comment]
Thought I had seen this more recently, but can't find any examples.
Builds are not public, but I'll gist one if it happens again.
