### ISSUE TITLE
CircleCI 1.0 EOL on August 31

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/terminus-build-tools-plugin#142]
CircleCI 1.0 will be EOL on August 31, 2018: https://circleci.com/blog/sunsetting-1-0/

The current stable version of this plugin is using CircleCI 1.0.  Is there any chance this will be updated to use 2.0 before 1.0 is gone?

**Comment by greg-1-anderson** [comment]
The master branch is using CircleCI 2.0.  `master` works pretty well; I should just tag a stable 2.x version.

**Comment by greg-1-anderson** [comment]
In theory you should be able to just merge the 2.x branch (master) into your project. However, I haven't done this. Your results may also vary depending on what customizations you have made.

**Comment by greg-1-anderson** [comment]
Fixed in master branch.
