### ISSUE TITLE
Bitbucket Support

### ISSUE THREAD

**Issue by ari-gold** [pantheon-systems/terminus-build-tools-plugin#145]
We've had some interest in Bitbucket support (WIP PR: #136)

Creating this issue to help us gauge interest level.

Bitbucket + Circle CI support would likely come first, but please add a comment to this issue if you're interested in using Bitbucket along with another test service (e.g. Jenkins)

If you'd like Bitbucket support, please add your +1 to this issue. Thanks!

**Comment by rick02840** [comment]
We'd love Bitbucket + Circle CI support.  I've used the Pantheon Github > Circle > Pantheon and at works great.  But we are kind of locked into using Bitbucket, so....

**Comment by asacolips** [comment]
Definitely interested in this. Lack of support (or even documentation on configuring a similar composer-based CI workflow sans Build Tools) has been a potential blocker for me.

**Comment by tmountjr** [comment]
Tried out the GitHub version and it's fantastic, but we've already sunk a lot of money into our Atlassian infrastructure, and in order to manage this with our clients we'd have to shell out extra money each month for GH private repos as well. Integrating this with Bitbucket would let us do the best of both worlds.

**Comment by bobreichard** [comment]
+1 Very interested in Bitbucket + Circle CI support. GitHub would be an extra expense for us moving to Pantheon, so lack of Bitbucket support becomes part of the decision process.

**Comment by philltran** [comment]
+1 for Bit Bucket support. Thanks

**Comment by dww** [comment]
+1 for BitBucket + CircleCI + buildtools support at Pantheon. Having to either pay for private GH repos or suffer with trying to build a site in a public repo (especially trying to store config, which is often full of sensitive stuff, API keys, SMTP authentication credentials, etc!) is a big blocker to wider adoption for me and my projects.  I'd much rather host the sites in private BitBucket repos.

**Comment by greg-1-anderson** [comment]
BitBucket support is well on its way! Thanks to the work of @NickWilde1990 and @philltran, BitBucket support has been rolled into the master branch of this repository. I have gone ahead and tagged a 2.0.0-beta1 release of this tool.

To try out BitBucket support, install 2.0.0-beta1 locally, run `build:project:create` with `--git=bitbucket`, and then make sure that the `.circleci/config.yml` uses the following Docker image:
```
    - image: quay.io/pantheon-public/build-tools-ci:3.x
```
The first build will probably fail until you update the version of the docker container as shown above.

This is a preview release. Once we have some positive feedback, we'll tag 2.0.0 stable here, and make the 3.x branch of the docker container the default for all new sites created with the Terminus Build Tools plugin.

**Comment by philltran** [comment]
Thanks @NickWilde1990 for all your work on this too. 

Congrats on the new job.

**Comment by aaronbauman** [comment]
+1 for more bitbucket support

Jumping in here from #109 : build:env:delete:ci still fails.

**Comment by alphex** [comment]
I would love bitbucket + pipelines support.   Thanks!

**Comment by jeffreynolte** [comment]
+1 on this!

**Comment by nelsonamaya82** [comment]
+1 for BitBucket + pipelines support. Thanks!

**Comment by mannuel** [comment]
+1 for more bitbucket support

**Comment by adamf321** [comment]
+1 for bitbucket pipelines!

**Comment by arzola** [comment]
+1 for bitbucket pipelines!

**Comment by ataylorme** [comment]
We have determined there is a demand for BitBucket + Pipelines support. For those that gave a +1 would you be willing to/ be interested in:

- Contributing to the work needed to support BitBucket + Pipelines
- Provide testing and feedback for BitBucket + Pipelines
- Help with documentation BitBucket + Pipelines
- All of the above!

**Comment by aaronbauman** [comment]
Yes, all of the above!

**Comment by philltran** [comment]
All the above for me too!

**Comment by alphex** [comment]
@ataylorme  --  happy to provide testing and feed back.   I keep saying I want to write documentation, but never find the time.  (maybe this time?)

**Comment by ataylorme** [comment]
Thank you @aaronbauman, @philltran and @alphex. We need to define the work to be done some more, at which point I'll reach out to you with areas where you can provide help.

**Comment by vinmassaro** [comment]
@ataylorme Can definitely help with testing, thanks!

**Comment by jeffreynolte** [comment]
All of the above!

**Comment by nelsonamaya82** [comment]
Of course! All of the above!

**Comment by mpaladino** [comment]
+1 one of our customers is requesting BB + Pipelines too. @ari-gold

**Comment by ataylorme** [comment]
Hi all! I posted [a status update and a request for feedback on the Build Tools project in the Pantheon forum](https://discuss.pantheon.io/t/terminus-build-tools-status-and-request-for-feedback/482).

It would help us out if you take the time to read it and answer the questions and leave feedback in the forum thread.

**Comment by ataylorme** [comment]
Work for BitBucket support is underway. Here is a quick inventory of where we are so far:

- [x] `build:project:create` support
  - [ ] Default `ci` to `pipelines` instead of `circle` for BitBucket
- [x] `build:env:delete` support
- [ ] `commentOnCommit` (link to multidev on PR)
- [ ] `bitbucket-pipelines.yml` for `example-wordpress-composer`
  - https://github.com/pantheon-systems/example-wordpress-composer/pull/171
- [ ] `bitbucket-pipelines.yml` for `example-drops-8-composer`
- [ ] Quicksilver pushback
- [ ] Composer Lock Updater job scheduled

**Comment by alphex** [comment]
This is exciting!
Got a bug report, if this is the right place.

I ran the command that @ataylorme posted just above ^ 

And it ran pretty much flawlessly except for two things.

First: I had to remove my organizational UUID, cause it wasn't recognizing it.   

```
 [CompletionWrapper]  Could not find an user-organization membership identified by 21b3c7e6-ced8-471d-91da-c3a14f1f2ca8.
 [CompletionWrapper]  Exit code 1
```

So I removed that line from the command, and it progressed to completion, except...
Despite creating a repo on bitbucket.
I can't find the pantheon site, lol.
It's not on my user dashboard, and when I try to build the URL by hand with the UUID it gave me, it just bounces me back to my user dashboard.   Ha!

Here's a relevant part of the terminal output 
```
[Progress] Create Git repository ABP0
 [notice] Creating repository alphex/abp0
 [notice] Call Bitbucket API: PUT repositories/alphex/abp0
 [notice] Executing git init
Initialized empty Git repository in /private/var/folders/j4/92r8nmpx1xbbphtydskgjbmc0000gn/T/local-siteG9M69L/ABP0/.git/
 [notice] Executing git remote add origin 'git@bitbucket.org:alphex/abp0.git'
 [notice] The target is alphex/abp0
 [Progress] Create Pantheon site abp0
 [notice] About to create Pantheon site abp0 in  with upstream empty
 [abp0] Creating a new Pantheon site abp0
 [notice] Deploying empty to Pantheon site
 [notice] Deployed CMS
 [notice] Created a new Pantheon site with UUID b7acc85c-e20f-4ffe-bbc2-501fbaccd490
 [Progress] Make initial commit
```

Here's the repo URL https://bitbucket.org/alphex/abp0/src/master/ which appears to be correct.

In the future, will we be able to make this private?   I assume?

Thank you all again for the hard work.

**Comment by aaronbauman** [comment]
Looks like this URL is working: http://dev-abp0.pantheonsite.io/
Weird behavior from dashboard though - I haven't run into that in my scant testing.

For the "--team" flag, it's working for me using our agency handle rather than uuid (from `terminus org:list`)

Also you can use the "visibility" flag to create a private repo, as of https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/226

Putting it altogether, my command looks like this:
```
terminus  build:project:create --org=messageagency --team=message-agency  --label="TEST LABEL" --email="XXX@XXX.com" --stability=dev --git=bitbucket --visibility=private --admin-password=XXXX --admin-email=XXX@XXX.com test-site
```

Notes: 
  - the `--org` flag is our bitbucket handle.
  - using `--git=bitbucket` changes the default CI provider to pipelines

**Comment by philltran** [comment]
@alphex I think the pantheon team flag is what will ink the site to your Pantheon dashboard.

**Comment by ataylorme** [comment]
Hi all,
If you need more information on the available parameters try `terminus build:project:create -h` or [check out the documentation for `build:project:create`](https://github.com/pantheon-systems/terminus-build-tools-plugin#buildprojectcreate).

@philltran is correct that `--team` is for the Pantheon org and `--org` is for the Git provider organization. Both are optional. `--team` can be either a Pantheon org UUID or machine name, both if which you can get from `terminus org:list`.

Hope that helps!

**Comment by ataylorme** [comment]
> Got a bug report, if this is the right place.

I think ideally bug reports would be in new issues so we can keep the conversation here focused on progress updates for BitBucket.

**Comment by nelsonamaya82** [comment]
Hi @ataylorme,
I've been doing some tests with this `build:project:create` command and it's really cool! However I'm facing an issue on Bitbucket: After pushing some code to master and running my pipelines, when I get to the command:

`rsync -a web/wp/wp-content/mu-plugins/pantheon web/wp/wp-content/mu-plugins/pantheon.php web/wp-content/mu-plugins/`

I get this error:

`rsync: chgrp "/opt/atlassian/pipelines/agent/build/web/wp-content/mu-plugins/pantheon" failed: Operation not permitted (1)`

I'm not sure if it's a bug or something I'm doing wrong.

**Comment by ataylorme** [comment]
@nelsonamaya82 I've been testing some BitBucket items and they are having an outage. It seems like it also might be a file permissions issue. Can you move this to a new GitHub issue on https://github.com/pantheon-systems/example-wordpress-composer?

I would like to keep this thread for updates/feedback and not bug reports

**Comment by nelsonamaya82** [comment]
Hi @ataylorme,
When I create a new project and set the git repo as Bitbucket, once this project is created in Bitbucket it says "No linked project was found for this repo.". Do you know how can I set a BB project?

I think there could be 2 ways to do this (but couldn't find any documentation about it):

1. `--org="MyBBOrganization/My project name"`
2. Or in the target value, like `"My project name/mi-repo-name"`

Thanks.

**Comment by ataylorme** [comment]
@nelsonamaya82 you are close. You do need `--org` but only the organization name goes there, not the project name.

Here is an example:

```
terminus build:project:create \
--org="some-bitbucket-org"
--git=bitbucket \
--ci=pipelines \
--stability=dev pantheon-systems/example-drops-8-composer:dev-master \
my-build-tools-project
```

You will need to replace `some-bitbucket-org` and `my-build-tools-project` with actual values to use and change `example-drops-8-composer` to `example-wordpress-composer` for WordPress instead of Drupal 8.

Note that `--stability=dev pantheon-systems/example-drops-8-composer:dev-master` is only needed to get the latest changes in our example repo. BitBucket work is still in progress so that won't be necessary once we make a stable `2.0` release of Build Tools

**Comment by aaronbauman** [comment]
`--ci` argument can be left empty, defaults to pipelines if `bitbucket` is specified for `--git`

If you want to make it explicit, I think it needs to be `--ci=bitbucket-pipelines`

**Comment by ataylorme** [comment]
> `--ci` argument can be left empty, defaults to `pipelines` if `bitbucket` is specified for `--git`

Updated the example command above

**Comment by nelsonamaya82** [comment]
> You will need to replace `some-bitbucket-org` and `my-build-tools-project` with actual values to use

Thanks @ataylorme, that's how I'm doing it right now, but the repo is not assigned to any project in Bitbucket and I get that message. This is my command:

```terminus build:project:create \
--team="My Team" \
--email="developer@myteam.com" \
--admin-email="developer@myteam.com" \
--admin-password="cms-admin-password" \
--git=bitbucket \
--org=MyBitbucketOrg \
--stability=dev \
--visibility=private \
--label="Label project name" \
pantheon-systems/example-wordpress-composer:dev-master \
my-project-name```

After running the command, it creates the repo in a random project inside my organization in Bitbucket, and the message there is:

`No linked project was found for this repo. Head on over to Rollbar.com to set it up.`

**Comment by jasonpierson** [comment]
+1 for bitbucket pipelines

**Comment by sugaroverflow** [comment]
👋  hey everyone - thanks so much for this great discussion and expressing your interest in Bitbucket support. At this time, we're working hard to release Build Tools 2.0 with Bitbucket support in the next few weeks. 

I'm going to go ahead and close this issue. In the future, feel free to open another issue if you're using Build Tools + Bitbucket and come across an issue. 

Thank you 🙌
