### ISSUE TITLE
How do I move my Drupal 8 site's GitHub repository to a GitHub Organization?

### ISSUE THREAD

**Issue by ssw3r** [pantheon-systems/terminus-build-tools-plugin#146]
I created my site using Terminus, which created a Drupal 8 site, Github Repository in my developer account, and CircleCI account. I need to move the repository to a GitHub organization that I am the owner of. Is this possible with Terminus?

**Comment by greg-1-anderson** [comment]
The credentials that are set up on CircleCI include:

- ssh key to push to Pantheon (with the corresponding public key on Pantheon)
- GitHub token that is passed to Pantheon for the Quicksilver pushback

If you move your GitHub repository, none of these credentials need to change. There are also implicit credentials managed by GitHub and Circle that allow the GitHub notification to start up tests on Circle. You might need to unfollow and refollow your project in Circle to make the builds continue to happen after the move, or it might just work.

So, in theory you should be able to just move your repo in the GitHub admin interface as usual. My one big disclaimer is that I have never actually done this. Please post your experiences here & let us know if it worked (or, conversely, post error messages here if there are problems that you need help resolving).

**Comment by ssw3r** [comment]
I moved it... will let you know if I have problems. Thanks!
