### ISSUE TITLE
CircleCI fails for pantheon/01-prepare with "permission denied"

### ISSUE THREAD

**Issue by ptmkenny** [pantheon-systems/terminus-build-tools-plugin#153]
Just made a new site with 2.0.0-beta1.  After installing, the first build_deploy_and_test fails with a permission denied error:

```
#!/bin/bash -eo pipefail
./.circleci/scripts/pantheon/01-prepare
/bin/bash: ./.circleci/scripts/pantheon/01-prepare: Permission denied
Exited with code 1
```

I checked the ./.circleci/scripts/pantheon/ directory on my local machine, but the permissions seem OK:

```
-rwxrwxrwx 1 user  484 Oct 18 19:58 01-prepare
-rwxrwxrwx 1 user  950 Oct 18 19:58 02-init-site-under-test-clone-existing
-rwxrwxrwx 1 user  507 Oct 18 19:58 02-init-site-under-test-reinstall-new
-rwxrwxrwx 1 user  230 Oct 18 19:58 03-post-test
-rwxrwxrwx 1 user  745 Oct 18 19:58 04-merge-master
-rwxrwxrwx 1 user  289 Oct 18 19:58 09-cleanup-fixtures
```

I made a code commit locally and pushed it to github; the triggered CircleCI build_deploy_and_test job also failed with the same error.  The "build" job is OK, but "build_deploy_and_test" fails.

**Comment by greg-1-anderson** [comment]
Odd; I have never seen that.

**Comment by greg-1-anderson** [comment]
I'm not sure why this would fail for you but work in many other instances without the explicit call to `bash`, but if the tests pass, I'd accept a PR that made this change in our config file.

**Comment by ataylorme** [comment]
Closing this out as it seems you got things working.

**Comment by ptmkenny** [comment]
I just set up a new site with the most recent version of build tools and had the same issue again, fixed in the same way.

I would send you a PR but I couldn't find the script to edit in the repo; it seems to be automatically generated in a way I don't understand...
