### ISSUE TITLE
BT-23: Unhelpful error messages when user exceeds sandbox quota

### ISSUE THREAD

**Issue by grasmash** [pantheon-systems/terminus-build-tools-plugin#156]
When executing `terminus build:project:create d8 pantheon-d8-composer-project` on an account that already has the maximum number of sandboxes, the only displayed error is: "The operation failed to complete." It took a long time to guess the root cause.

**Comment by sugaroverflow** [comment]
@aweingarten recently opened #376 for the same issue, so closing this one (I'm cleaning up old issues)  and moving the discussion there. Thanks!
