### ISSUE TITLE
Add option for `build:env:push` command to include message

### ISSUE THREAD

**Issue by JulienMelissas** [pantheon-systems/terminus-build-tools-plugin#161]
Currently, as per [this line](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Commands/BuildToolsBase.php#L767), deploys are all marked as "Build assets for `$env_label`" which isn't too helpful contextually in the Pantheon dashboard. It would be awesome if we were able to optionally pass a `--message` param to the push command.

First I'm just gauging interest. I'd be happy to contribute if pointed in the right direction.

**Comment by ataylorme** [comment]
@JulienMelissas I think having a customizable message for `build:env:push` would be a good enhancement.

This project, like Terminus itself, uses Symfony Console which has support for [optional command options](https://symfony.com/doc/current/console/input.html#using-command-options).

Since this plugin is mostly used in scripted environments I think that would be the best approach, as opposed to a user prompt or something else.

Feel free to make a PR if you are comfortable.

**Comment by greg-1-anderson** [comment]
Most of the time, `build:env:push` will run during the automation step of a pull request. Actually, for most users, it is called implicitly as part of `build:env:create`, if the multidev already exists. As a result, there generally isn't a good opportunity for a user to supply a message.

We could in theory look at the commits on the branch, and craft a message from those. There may be multiple commits, though, so there is some question about how one would best summarize them to get the best first line (for the dashboard display).

A PR to add `--message`, whether or not `build:env:create` attempted to use it, would be welcome.

**Comment by ataylorme** [comment]
> We could in theory look at the commits on the branch, and craft a message from those. There may be multiple commits, though, so there is some question about how one would best summarize them to get the best first line (for the dashboard display).

Right now build tools is using `git commit -m`, which only sends a short, one-line commit message. 

`git commit` supports commit messages with multiple lines as well. For example, if you omit the `-m` with `git commit` a text editor will open and you will be prompted for a commit message which can have multiple lines.

That isn't practical in a scripted setting but [`git commit`](https://git-scm.com/docs/git-commit) can have multiple `-m` options, each one of them being turned into a line of the commit message. We could use this to loop through all previous commit and add their message, hash of the commit, or other useful information.

`--file` can also be used instead to read the commit message from a file, which might be a better approach than appending multiple `-m` options.

**Comment by ataylorme** [comment]
I forgot to attach the example screenshot of the Pantheon supporting commit messages with multiple lines

![pantheon-dashboard-git-commit-log](https://user-images.githubusercontent.com/2133004/50983814-2c841300-14b5-11e9-8f41-a6d688a5ff3e.png)

**Comment by greg-1-anderson** [comment]
Ah, I thought that the dashboard only displayed the first line or two of a multiline message.

In any event, those are all good suggestions.

**Comment by JulienMelissas** [comment]
> git commit supports commit messages with multiple lines as well

Supporting multi-line commit messages seems like a bit more than we would need, imo, but I understand the why someone would want that I guess. For my PR I will focus on just supporting the `-m` part for the `build` command and we could build on that in the future.
