### ISSUE TITLE
Document lack of Windows support

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#162]

**Comment by sugaroverflow** [comment]
From https://pantheon.io/docs/terminus 

> Install Terminus on macOS or Linux. Windows 10 users can install the Windows Subsystem for Linux. For details on legacy versions of Terminus, see Legacy Terminus Versions.

Should include this with the work on #221

**Comment by sugaroverflow** [comment]
Done with https://github.com/pantheon-systems/documentation/pull/5444/commits/29ef53e8d48b0f133a565480b1dbb2e62b299d3f
