### ISSUE TITLE
Allow The Merge Command To Persist the Multidev Environment

### ISSUE THREAD

**Issue by populist** [pantheon-systems/terminus-build-tools-plugin#17]
Currently the terminus build-env:merge command will delete the Multidev environment after a successful merge, but this isn't always wanted by developers since they may be reusing the Multidev environment.

Could we have an option to allow the Multidev environment to persist?

**Comment by greg-1-anderson** [comment]
Yes; in fact, I think that should be the default.

**Comment by greg-1-anderson** [comment]
Fixed by d6c0efa -- LMK if that does the trick for you.

**Comment by populist** [comment]
Good to go!
