### ISSUE TITLE
Moved Github repository from personal account to org

### ISSUE THREAD

**Issue by Nikro** [pantheon-systems/terminus-build-tools-plugin#203]
Hi there,

I ran into an issue today, I've used build tools (beta12) with terminus 2.0.1 to create a website. Then, once everything was configured properly, I decided to move the repository under the organization and now I get an error, while deploying:

```
#!/bin/bash -eo pipefail
./.ci/scripts/01-prepare
Begin build for ci-49. Pantheon test environment is offpeak-yarra-weddings.ci-49
Terminus 2.0.0
[error] Remote repository mismatch: local repository, webprophets/offpeak-yarra-weddings is different than the repository Nikro/offpeak-yarra-weddings associated with the site offpeak-yarra-weddings. 
Exited with code 1
```

I've read somewhere that removing all `ci-*` envs might help, but running this command also triggers same error:

```
 terminus build:env:delete:ci offpeak-yarra-weddings
 [notice] [...]/build-metadata.json => /tmp/build-metadata.json
 [error]  Remote repository mismatch: local repository, webprophets/offpeak-yarra-weddings is different than the repository Nikro/offpeak-yarra-weddings associated with the site offpeak-yarra-weddings. 
```

I tried running `terminus build:project:repair` - replaced all the tokens, but that didn't help. My guess is that `terminus build:project:repair` should offer an ability to change the Github details in `build-metadata.json`.

What do you recommend?

**Comment by greg-1-anderson** [comment]
The problem you are having is that each individual multidev contains a copy of build-metadata.json, and the `build:project:repair` command does not touch these.

Use `terminus env:delete` to remove all of your `ci-*` and `pr-*` multidevs, and things should be fine again (assuming that `build:project:repair` did, in fact, do its thing correctly).

**Comment by Nikro** [comment]
Okay, manually running `terminus env:delete <PROJECT>.<ENV>` (where <ENV> is `ci-X` and `pr-X`, you can find those by `terminus env:list <PROJECT>`) - *worked*.

Thanks a lot! :) Hope this issue will be useful for others.
