### ISSUE TITLE
Unable to login to BitBucket

### ISSUE THREAD

**Issue by stephencapellic** [pantheon-systems/terminus-build-tools-plugin#205]
I'm new to Pantheon Build Tools. I am attempting to run the `terminus build:project:create` command with the `--git=bitbucket` argument. I am then prompted, "Enter your Bitbucket account password or an app password." I enter my BitBucket account password (and have trie two different App Passwords) but am always met with the response, "Your provided username and password or app password could not be used to authenticate with the BitBucket service. Please re-enter your credentials." I am then asked to enter my BitBucket username and password or app password. I am unable to authenticate.

I am not given any feedback from Terminus whenever I type or paste in my username and password at the prompts, so I'm not sure if the issue is with my entry or with Terminus or beyond.

Apparently people are using the BitBucket integration, I'm hoping someone can point out the mistake I'm making.

**Comment by ataylorme** [comment]
> Apparently people are using the BitBucket integration

Hi @stephencapellic the BitBucket work is still in progress and very much incomplete. You can use it but until Terminus Build Tools `2.0` launches BitBucket support is unstable.

That being said, thank you for reporting the issue. We will keep it in mind when working on the BitBucket support
