### ISSUE TITLE
Prepare Database takes 3 minutes to run

### ISSUE THREAD

**Issue by msauberPrincipal** [pantheon-systems/terminus-build-tools-plugin#206]
The command "prepare database for site-under test" takes 3.5 minutes to run in circleci. This is very long and disrupts our ability to deliver quickly. The script is "02-init-site-under-test-clone-existing" and the script is below
#!/bin/bash

set -eo pipefail

terminus -n env:wake "$TERMINUS_SITE.dev"
terminus -n build:env:create "$TERMINUS_SITE.dev" "$TERMINUS_ENV" --yes --clone-content --notify="$NOTIFY"

terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- updatedb -y

terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" cr

if [ -f "config/system.site.yml" ] ; then
  terminus -n drush "$TERMINUS_SITE.$TERMINUS_ENV" -- config-import --yes
fi

**Comment by ataylorme** [comment]
@msauberPrincipal `build:env:create` created a new multidev environment. The act of creating the environment on Pantheon takes about 2-3 minutes. There isn't a way to speed that up.

> This is very long and disrupts our ability to deliver quickly. 

Can you expand on this a bit more? _How_ is the CI job taking 3.5 minutes impacting your team/workflow?

**Comment by msauberPrincipal** [comment]
Thank you for quick response! 

We do lots of mobbing and end up waiting the 3.5 minutes to build and we haven't even added automated functional tests yet which I assume will take more time and put us in 10 minute build range. It's longer then our team would like. Could we preinstall database or are we really sol?

**Comment by greg-1-anderson** [comment]
It might be possible to change the logic of the script to choose from a pool of existing pull requests rather than make a new one every time. Note that `build:env:create` will re-use an existing multidev if it already exists, so you don't need to change this script, you could just change the calculation of TERMINUS_ENV to use the modulo of the pull request number, or maybe something more sophisticated than that.

You'd run into some uncomfortable problems if you had collisions in the selected multidevs for different pull requests, though.

**Comment by ataylorme** [comment]
> we haven't even added automated functional tests yet which I assume will take more time and put us in 10 minute build range

One strategy here might be to only do long-running tests once per pull request/branch, either right before it is about to be merged (after code review) or bringing it into a `develop` branch or similar where a full test suite runs before merging to `master`.

Some tests, like unit tests and code sniffing, run quickly and can be done without the multidev. Those should probably always run as you can take advantage of parallel jobs so they aren't adding to the overall build time.

**Comment by rvtraveller** [comment]
I hear the pain here -- I had a site at one point that took 30-40 minutes to create a multidev environment. We had to modify our workflow.

One approach you might look at taking (outside of the provided setup) is to maintain a "pool" of multidev environments for testing -- 5-10 depending on how many multidevs you want to leave available for other things. Those multidevs would always be ready to have tests executed against them and setting them back to the "good" state (as they would be when you create from dev) can happen at the end of your pipeline as a separate job in Circle. Something like the [Terminus Dibs Plugin](https://github.com/terminus-plugin-project/terminus-dibs-plugin) could be used to control where tests are running.

**Comment by msauberPrincipal** [comment]
Thank you everyone for the comments! We will follow the advice given!
