### ISSUE TITLE
Allow build tools to be used without multidev

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#219]
As a Pantheon customer who loves CII want to be able to use build tools even when I don’t have access to multidev

Done when:

- Build tools can be used without access to multidev on Pantheon
- Pushing code to the master branch pushes build artifacts to dev-master
- Pull requests / other branches do not build artifacts
- Jobs should complete as early as possible if multidevs are not available

Notes:

If it is not possible to automatically determine if multidev access has been acquired since the project was created, it would be desirable if there was some way (e.g. an environment variable) that users could adjust to turn the feature on.

**Comment by sugaroverflow** [comment]
Closing out old issues. Will make a note of this for future functionality. Thank you!  😄
