### ISSUE TITLE
Please do not nuke all .git files from all sibling directories recursively

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/terminus-build-tools-plugin#22]
I'm following the quickstart command for the first time, and it fails.
Fine, expected.

However, I get this failure, right after the following output from terminus:

>  [notice] Push code to Pantheon
>  [notice] Pushing code to dev using branch {branch}.
> fatal: Not a git repository (or any of the parent directories): .git
>  [notice] Running git -C /private/var/folders/sd/.../T/local-siteIqzSPP/ma-composer-test remote add pantheon ssh://codeserver.dev....@codeserver.dev.....drush.in:2222/~/repository.git
>  [notice] Set build-metadata.json to {"url":"","ref":"master","sha":"...","comment":"Initial commit","commit-date":"2017-04-14 16:03:27 -0400","build-date":"2017-04-14 20:03:31 +0000"}.
> 
> "Failed to remove directory "/Users/bauman/Sites/oldd8/.../drupal-project/drupal-project/vendor/jcalderonzumba/mink-phantomjs-driver/.git/refs/tags"

Hmm, why is terminus removing my .git files from an unrelated project?

I go to inspect, and sure enough terminus has nuked ALL my .git directories from ALL sibling directories relative to cwd, recursively, destroying all my project .git setups until it reached this error and finally died.

This is very, very not ideal to say the least.
Please, if the plugin could not do this anymore, that would be great.

**Comment by greg-1-anderson** [comment]
Fixed in #25. Sorry for the inconvenience.

**Comment by greg-1-anderson** [comment]
Merged to master.
