### ISSUE TITLE
Make the update-db + cache-clear functions a responsibility of build:env:create

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#222]
it would only have to do it if the multidev was re-used (not created this run) and the --clone-content option was specified to copy the database.

See [this discussion](https://github.com/pantheon-systems/example-wordpress-composer/pull/86#pullrequestreview-227475379)

**Comment by sugaroverflow** [comment]
This has been taken care of in the multidev creation command so closing for now.
