### ISSUE TITLE
Cleanup failed build?

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/terminus-build-tools-plugin#23]
Now that my build is apparently failed, I can't just run the command again because the git repo still exists with that name, as well as the pantheon site. 
Is there a way to confirm that it's indeed broken?
Is there a way to retry the build?
Is there a quick/easy way to clean up a failed build?

**Comment by greg-1-anderson** [comment]
While there is a `build-env:obliterate` command, this only works on sites that were completely created -- for safety reasons. For the time being, you will need to manually delete the GitHub and Pantheon sites.

I will improve the error recovery for failed commands, and make them delete any github or Pantheon site that may have been created prior to a failed run.

**Comment by greg-1-anderson** [comment]
Fixed in #25

**Comment by greg-1-anderson** [comment]
Merged to master.
