### ISSUE TITLE
The latest release contains a composer.lock file which conflicts with Terminus' composer.lock file

### ISSUE THREAD

**Issue by claylibrarymarket** [pantheon-systems/terminus-build-tools-plugin#251]
The `composer.lock` file should be adjusted to match Terminus' `composer.lock` file or be removed (preferred) as to avoid conflicts with package versioning.<sup>\[1]</sup>

\[1]: https://github.com/pantheon-systems/terminus/blob/master/src/Plugins/ComposerDependencyValidator.php#L106

**Comment by ataylorme** [comment]
@claylibrarymarket thanks for opening an issue. I think this is a duplicate of https://github.com/pantheon-systems/docker-build-tools-ci/issues/36

The conflict only arises when Terminus and Build Tools are installed with dev dependencies. You should install them using `--no-dev`.

**Comment by claylibrarymarket** [comment]
Thanks for the prompt response and the code reference; I'll update my build tools image accordingly.
