### ISSUE TITLE
Incomplete BitBucket Pagination Methods

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#253]
[`src/API/Bitbucket/BitbucketAPI.php`](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/API/Bitbucket/BitbucketAPI.php) has placeholder methods. These should be updated with proper logic to parse the BitBucket API.

- [ ] `isPagedResponse`
- [ ] `getPagerInfo`
- [ ] `isLastPage`
- [ ] `getNextPageUri`

**Comment by ataylorme** [comment]
See the [GitHub](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/API/GitHub/GitHubAPI.php) and [GitLab](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/API/GitLab/GitLabAPI.php) implementations for examples

**Comment by danielbachhuber** [comment]
@ataylorme What's the best way to reproduce this?

**Comment by ataylorme** [comment]
Pagination kicks in when there are more items returned by the API than can fit in a single request.

I'm not sure where pagination kicks in for BitBucket API requests but `terminus build:env:delete:pr` with a lot of open PRs would probably trigger it.

**Comment by ataylorme** [comment]
See https://developer.atlassian.com/bitbucket/api/2/reference/meta/pagination

**Comment by danielbachhuber** [comment]
It looks like `branchesForPullRequests()` is the only method that makes a `pagedRequest()`:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/637704d91a5c04232cf7e36269684890ab0d5dcc/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php#L127

`branchesForPullRequests()` is called by `eligibleIfClosedPrExists()`:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/9005ef39479fec0f7b7343b1ad4cd333f8b8aa3a/src/Utility/MultiDevRetention.php#L101-L104

**Comment by ataylorme** [comment]
Yes, `branchesForPullRequests()` is used by `build:env:delete:pr` to determine which multidev branches correspond with open PRs and which should be deleted (closed PRs).
