### ISSUE TITLE
--visibility=private ignored by bitbucket provider

### ISSUE THREAD

**Issue by campusphilly** [pantheon-systems/terminus-build-tools-plugin#255]
Build command:
`terminus  build:project:create --org=XXXX --team=XXXX  --label="Pipelines Test" --email="info@XXXX.com" --stability=dev --ci=bitbucket-pipelines --git=bitbucket --visibility=private --admin-password=XXXX --admin-email=info+pipetest@XXX.com pipe-test`

Expected behavior:
- private bitbucket repository

Observed behavior:
- public repo

**Comment by aaronbauman** [comment]
Oops, created with wrong user account.
Subscribing.

**Comment by ataylorme** [comment]
Closed by #256
