### ISSUE TITLE
Document required authentication details

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/terminus-build-tools-plugin#257]
When I tried to run `terminus build:project:create --team='Hand Built' --git=bitbucket wp bitbucket-test`, I saw:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36432/64611206-c45c3880-d385-11e9-84cc-5934a3e9ce9c.png">

I then looked at the README for whatever authentication I might need to do and didn't find any details.

After debugging, I discovered that this particular error was coming from Terminus. Logging out and logging back in solved the problem.

I also found reference to `BITBUCKET_USER` and `BITBUCKET_PASS` in the source code. From this, I deduced what I needed to do.

It would be helpful if these authentication details were documented in the README.

**Comment by ataylorme** [comment]
@danielbachhuber this definitely seems like a bug. You _should_ be prompted for any lacking credentials.

What versions of Terminus and Build Tools are you using?

**Comment by danielbachhuber** [comment]
Terminus 2.1.0 and Build Tools at 637704d91a5c04232cf7e36269684890ab0d5dcc

**Comment by danielbachhuber** [comment]
> You _should_ be prompted for any lacking credentials.

To clarify, I ended up setting `BITBUCKET_USER` and `BITBUCKET_PASS` _after_ fixing Terminus authentication and _before_ running `create-project` again. 

The specific issue is that authentication details need to be documented in the README. Sorry I wasn't more clear with my original report.

**Comment by ataylorme** [comment]
> The specific issue is that authentication details need to be documented in the README. Sorry I wasn't more clear with my original report.

If `BITBUCKET_USER` and `BITBUCKET_PASS` are not defined Build Tools should prompt you for them in an interactive way.

Being able to set the environment variables ahead of time is an added feature so `build:project:create` can be run in an automated way. This is a bug, not a documentation issues, as it is optional

**Comment by sugaroverflow** [comment]
Tested this with the different options and no previously loaded tokens and it is working correctly - prompts you for the auth details for the provider (and service). 

I also added a line to the new docs specifying that the installation will prompt you for these details (and how to set them up for github as an example). 

Thank you! 🙌
