### ISSUE TITLE
Confusing usage of `checkPagedCallback()`

### ISSUE THREAD

**Issue by danielbachhuber** [pantheon-systems/terminus-build-tools-plugin#266]
In working on #253, I see a call to `$this->checkPagedCallback()` when determining whether to iterate the API data:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/fd2a9e4c68e1fe9cd4bda1f4153cd7c60e584525/src/API/WebAPI.php#L55-L57

`$this->checkPagedCallback()` unexpectedly returns false for me.

`branchesForPullRequests()` (the only method I can see using `pagedRequest()`) passes through the `$callback` from `eligibleIfClosedPRExists()`, which appears to be the object instance:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/9005ef39479fec0f7b7343b1ad4cd333f8b8aa3a/src/Utility/MultiDevRetention.php#L101-L104

I guess it's an invalid callback to begin with?

It looks like the invalid callback landed in a mega commit: db590a9d2368632ab848736218b8b5d00e10c364

I'd think we wouldn't need a callback, and instead could use a method on `WebAPI`.

cc @greg-1-anderson

**Comment by ataylorme** [comment]
cc @rvtraveller as well.

**Comment by danielbachhuber** [comment]
> I guess it's an invalid callback to begin with?

I take it back. There's something magical/non-obvious going on here:

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/9005ef39479fec0f7b7343b1ad4cd333f8b8aa3a/src/Utility/MultiDevRetention.php#L124-L136

I don't fully understand what's going on though.

As currently implemented, `pagedRequest()` doesn't iterate all of my Bitbucket PRs in #267. If I refactor the `while()` statement to reference API response pagination data (see diff below), then all of my Bitbucket PRs are fetched as expected.

```php
-    public function pagedRequest($uri, $callback = null, $queryParams = [])
+    public function pagedRequest($uri, $queryParams = [])
     {
         $queryParams = $this->alterPagedRequestQueryParams($queryParams);
         $res = $this->sendRequest($uri, $queryParams, 'GET');
@@ -55,14 +55,15 @@ abstract class WebAPI implements WebAPIInterface, LoggerAwareInterface

         // Remember all of the collected data in $accumulatedData
         $accumulatedData = $resultData;
-        $isDone = !$this->checkPagedCallback($resultData, $callback);
+        $pager_info = $this->getPagerInfo($res);
+        $isDone = !$this->getNextPageUri($pager_info);

         // The request may be against a paged collection. If that is the case, traverse the "next" links sequentially
         // (since it's simpler and PHP doesn't have non-blocking I/O) until the end and accumulate the results.
         // Check if the array is numeric. Otherwise we can't consider this a collection.
         if ($this->isSequentialArray($resultData) && $this->isPagedResponse($res)) {
-            $pager_info = $this->getPagerInfo($res);
             while (($httpCode == 200) && !$isDone) {
+                $pager_info = $this->getPagerInfo($res);
                 $isDone = $this->isLastPage($uri, $pager_info);
                 $next = $this->getNextPageUri($pager_info);
                 if ($next == $uri) {
@@ -74,7 +75,6 @@ abstract class WebAPI implements WebAPIInterface, LoggerAwareInterface
                     $res = $this->sendRequest($uri, [], 'GET');
                     $httpCode = $res->getStatusCode();
                     $resultData = $this->getResultData($res);
-                    $isDone = !$this->checkPagedCallback($resultData, $callback);
```

**Comment by danielbachhuber** [comment]
> I don't fully understand what's going on though.

Now I understand!

Build Tools _first_ iterates all of the multidev environments, to **build a list of branches to look for**.

Then, Build Tools _only_ iterates the pull requests **until it has seen all of the pull requests associated with the existing multidev environments**. This is to mitigate having to iterate all pull requests each time.

The multidev environment I had originally, `pr-6`, existed in the first set of PRs, so Build Tools didn't need to make another API request.

I created a new multidev environment, `pr-18`, without a corresponding PR, and Build Tools iterated all Bitbucket PRs as expected.

**Comment by ataylorme** [comment]
@danielbachhuber do you mind making a PR with some code comments and/or adding the info to `DEVELOPMENT.md`? I would like for Build Tools to be less of a black box for those contributing

**Comment by danielbachhuber** [comment]
Sure, I'll do after my other PRs land.
