### ISSUE TITLE
Add build:self:info command

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#288]
This should show, at a minimum, the current version of the Build Tools plugin.

Optionally, notifying users that there is an update available as well.

**Comment by sugaroverflow** [comment]
@rvtraveller and I discussed this today, here's what we think is good for output:

- build tools version number
- installation directory
- which providers you have env variables set for (checks your auth tokens)

**Comment by rvtraveller** [comment]
So, the interesting thing here is that the "build tools version number" is really just an artifact of the tag in GitHub. There isn't a "file" or "variable" that ships with Build Tools that actually specifies a version number.

**Comment by sugaroverflow** [comment]
Oh hmm, instead of the version number, can we output something like:

- see release: (link to github releases)
