### ISSUE TITLE
Github api warning on create new project

### ISSUE THREAD

**Issue by mariacha** [pantheon-systems/terminus-build-tools-plugin#323]
I'm getting this automated email from Github:

> On February 7th, 2020 at 23:31 (UTC) your personal access token (XYZ) using Composer/1.9.2 (Linux; 4.15.0-1052-aws; PHP 7.3.13; CI) was used as part of a query parameter to access an endpoint through the GitHub API:

> [link to the tarball]

> Please use the Authorization HTTP header instead, as using the `access_token` query parameter is deprecated and will be removed July 1st, 2020.

I just installed the build tools last week, so I think I'm on the latest version. Is there some set up step I should have done differently, or is this going to be a problem come July?

**Comment by greg-1-anderson** [comment]
Are you using Build Tools 1.x or 2.x?

**Comment by mariacha** [comment]
It's the 2.x branch.

**Comment by greg-1-anderson** [comment]
Elsewhere someone said this message is literally coming from Composer, and is fixed in Composer 1.9.3.

I'll update the docker image to use the latest Composer.

**Comment by greg-1-anderson** [comment]
Docker image updated; the warning should go away if you are using the 6.x image in your builds.

**Comment by greg-1-anderson** [comment]
I also started builds on all of the other old branches, although I did not confirm if every branch automatically gets the latest version of Composer on a simple rebuild.

**Comment by mariacha** [comment]
I'll give it a shot and report back. Thanks!

**Comment by mariacha** [comment]
Looks like this is all fixed. Thanks so much!

**Comment by rjbain** [comment]
I upgraded to the 6.x image, but I'm still getting the notice from GitHub. 
```
  docker:
    - image: quay.io/pantheon-public/build-tools-ci:6.x
```
Thanks.

**Comment by greg-1-anderson** [comment]
The 6.x image is using Composer 1.10.9. Does the error message in the email say which application and version is being used?

It's after 1 July, so in theory, if there were any lingering access_token query parameters, then the build should be broken. Perhaps there was a soft extension of the deadline, though.

**Comment by rjbain** [comment]
Thanks, Greg. 
The email says it's using Composer/1.6.5 (Linux; 4.15.0-1077-aws; PHP 7.2.6; CI).

**Comment by greg-1-anderson** [comment]
When you run `composer --version`, what result do you get? I suspect that message is not coming from the `pantheon-public/build-tools-ci:6.x` image.

**Comment by rjbain** [comment]
Here's what I have locally:

$ lando composer --version
Composer version 1.8.0

$ composer --version
Composer version 1.6.2

**Comment by rjbain** [comment]
When I check the version during the build, it's reporting:
Composer version 1.6.5 
Could the image be cached, or is there somewhere else I need to change the image version?
Thank you.

**Comment by greg-1-anderson** [comment]
How are you checking the Composer version in the build?
```
$ docker run -it quay.io/pantheon-public/build-tools-ci:6.x bash
$ composer --version
Composer version 1.10.10 2020-08-03 11:35:19
```
Maybe you are using a different container for some build steps?

**Comment by rjbain** [comment]
Ah, I think I figured it out. It looks like we have people working on some old multidevs that haven't pulled in the upgraded image yet. Sorry for the bother, Greg. Thanks for your help!

**Comment by rjbain** [comment]
Hi @greg-1-anderson sorry to bug you with this again, but this issue is cropping up again. You mentioned that it might be coming from another image. I am seeing another image in my .circleci/scripts/config.yml file:

    build_theme:
      <<: *defaults
      working_directory: ~/example_drops_8_composer/
      docker:
        - image: circleci/node:8-stretch-browsers
        
Do you think this could be the culprit? Thank you!
