### ISSUE TITLE
Error on first time use.

### ISSUE THREAD

**Issue by alphex** [pantheon-systems/terminus-build-tools-plugin#33]
Running build-env for the very very first time, and getting this error.

Thanks!

`$ terminus build-env:create-project d8 duran-build --verbose

  [Pantheon\Terminus\Exceptions\TerminusException]
  The site name duran-build is already taken on Pantheon.

Exception trace:
 () at /Users/duran/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php:166
 Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->validateSiteName() at /Users/duran/vendor/consolidation/annotated-command/src/Hooks/HookManager.php:601
 Consolidation\AnnotatedCommand\Hooks\HookManager->callInjectConfigurationHook() at /Users/duran/vendor/consolidation/annotated-command/src/Hooks/HookManager.php:292
 Consolidation\AnnotatedCommand\Hooks\HookManager->initializeHook() at /Users/duran/vendor/consolidation/annotated-command/src/CommandProcessor.php:76
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /Users/duran/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:376
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /Users/duran/vendor/symfony/console/Command/Command.php:227
 Symfony\Component\Console\Command\Command->run() at /Users/duran/vendor/symfony/console/Application.php:852
 Symfony\Component\Console\Application->doRunCommand() at /Users/duran/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /Users/duran/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at /Users/duran/vendor/consolidation/robo/src/Runner.php:157
 Robo\Runner->run() at /Users/duran/vendor/pantheon-systems/terminus/src/Terminus.php:136
 Pantheon\Terminus\Terminus->run() at /Users/duran/vendor/pantheon-systems/terminus/bin/terminus:46

build-env:create-project [--org [ORG]] [--team [TEAM]] [--pantheon-site [PANTHEON-SITE]] [--label [LABEL]] [--email [EMAIL]] [--test-site-name [TEST-SITE-NAME]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--stability [STABILITY]] [--env [ENV]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-y|--yes] [--] <command> <source> [<target>]`

**Comment by alphex** [comment]
... sorry, more details.

that site name is NOT taken, it doesn't exist.    I've tried many variants of the site name, and still the same error.

**Comment by mojowill** [comment]
It might not exist in your dashboard, but it could exist already with someone else ;)

**Comment by greg-1-anderson** [comment]
Any resolution on this, @alphex? Is `build-env:create-project` working for you now? Try updating to the latest version.

**Comment by alphex** [comment]
No, nothing yet.
I haven't had time to dig back in to it... I will update and chase someone
down when i do :) . maybe next week?
ᐧ


] duran goodyear
] alphex information solutions, llc
] w: http://alphex.com // v: 267.225.7439 // e: duran@alphex.com

**Comment by e0ipso** [comment]
I had the same issue. Running: `terminus auth:login` solved it for me.

**Comment by greg-1-anderson** [comment]
Oh, yes, you must authenticate first! I will test that and improve error checking.

**Comment by alphex** [comment]
I'm not saying thats NOT what my problem was -- but I'd be surprised if I
wasn't AUTHed, since I use terminuse remote:drush daily (hourly, maybe
every few minutes... ok, I admit, its a nervous twitch and I invoke it when
I blink).

ᐧ


] duran goodyear
] alphex information solutions, llc
] w: http://alphex.com // v: 267.225.7439 // e: duran@alphex.com

**Comment by greg-1-anderson** [comment]
Someone else had this problem, and running `terminus auth:login` solved their problem as well.

**Comment by alphex** [comment]
@greg-1-anderson 
Still getting the same error.

`terminus auth:login' works, or says it does.

> $ terminus auth:login
> [notice] Found a machine token for duran@alphex.com.
> [notice] Logging in via machine token.

`$ terminus build-env:create-project d8 erc-public --verbose`

screen shot of error : http://z.alphex.io/2017-07-20_19-53-21--achqq.jpg

text dump of error



  [Pantheon\Terminus\Exceptions\TerminusException]
  The site name erc-public is already taken on Pantheon.


Exception trace:
 () at /Users/duran/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php:166
 Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->validateSiteName() at /Users/duran/vendor/consolidation/annotated-command/src/Hooks/HookManager.php:601
 Consolidation\AnnotatedCommand\Hooks\HookManager->callInjectConfigurationHook() at /Users/duran/vendor/consolidation/annotated-command/src/Hooks/HookManager.php:292
 Consolidation\AnnotatedCommand\Hooks\HookManager->initializeHook() at /Users/duran/vendor/consolidation/annotated-command/src/CommandProcessor.php:76
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /Users/duran/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:376
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /Users/duran/vendor/symfony/console/Command/Command.php:227
 Symfony\Component\Console\Command\Command->run() at /Users/duran/vendor/symfony/console/Application.php:852
 Symfony\Component\Console\Application->doRunCommand() at /Users/duran/vendor/symfony/console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /Users/duran/vendor/symfony/console/Application.php:122
 Symfony\Component\Console\Application->run() at /Users/duran/vendor/consolidation/robo/src/Runner.php:157
 Robo\Runner->run() at /Users/duran/vendor/pantheon-systems/terminus/src/Terminus.php:136
 Pantheon\Terminus\Terminus->run() at /Users/duran/vendor/pantheon-systems/terminus/bin/terminus:46

build-env:create-project [--org [ORG]] [--team [TEAM]] [--pantheon-site [PANTHEON-SITE]] [--label [LABEL]] [--email [EMAIL]] [--test-site-name [TEST-SITE-NAME]] [--admin-password [ADMIN-PASSWORD]] [--admin-email [ADMIN-EMAIL]] [--stability [STABILITY]] [--env [ENV]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-y|--yes] [--] <command> <source> [<target>]

**Comment by alphex** [comment]
Updated to 1.4.1
Still receiving same error message.

**Comment by alphex** [comment]
WAIT, scratch that...   my alias is pointing to a very old version of terminus :(

**Comment by alphex** [comment]
Yeah, that did it.

Updated the CORRECT terminus.

We can close this now.

**Comment by greg-1-anderson** [comment]
Glad to hear an upgrade solved this issue for you.

**Comment by cleverington** [comment]
Just as a bump, might consider altering the error-text to request `terminus auth:login` be performed when continually seeing the error.

**Comment by greg-1-anderson** [comment]
Tracking in https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/115
