### ISSUE TITLE
Use a non-packagist repository

### ISSUE THREAD

**Issue by abendy** [pantheon-systems/terminus-build-tools-plugin#340]
Can I use a local or public hosted (e.g. GitHub) repository to create a new build? I've seen a few previous issues (e.g. #126) but I haven't found anything conclusive or descriptive solution.

**Comment by sugaroverflow** [comment]
Hi @abendy, you should definitely be able to use a hosted Github/Gitlab/Bitbucket project to create a new build. 

Build Tools creates public projects by default, but you can use the `--visibility` command option to set that: 

--visibility | The visibility of the project. Defaults to "public". Use "public" or "private" for GitHub and "public", "private", or "internal" for GitLab
-- | --

**Comment by abendy** [comment]
Bad wording on my part, I meant as a source for the new build, not to host new build at.

Is there a better way to do this as a single command, versus...

`
git clone git@github.com:pantheon-systems/example-wordpress-composer.git
terminus build:project:create ./example-wordpress-composer new-site
`

**Comment by matbrady** [comment]
Ideally we could reference a git url to use as the template, and not even have to clone our template locally. It would be great to be able to reference a release version or branch.  

```
terminus build:project:create git@github.com:ORGAGNIZATION/example-wordpress-composer.git:BRANCH new-site
```

Some justification:
- unnecessary overhead to register and link repo to Packagist
- Packagist [discourages publishing forks](https://packagist.org/packages/submit)
  > Do not submit forks of existing packages. If you need to test changes to a package that you forked to patch, use VCS Repositories instead. If however it is a real long-term fork you intend on maintaining feel free to submit it.

**Comment by adam-delaney** [comment]
We are interested in using a Github private repository as well. Any updates on if this is supported?

**Comment by sugaroverflow** [comment]
Thank you so much for your interest! Due to a lack of capacity, we won't be able to build this feature at this time. 

If you have a solution in mind though, I'd be happy to review a PR. There might be a way to make this work if your local composer could knew of your private upstream. 

In the meantime, I'm tagging this as an enhancement and will put it on the radar as the project undergoes transition. Hopefully with more resources, we'll be able to support more features soon!

**Comment by sugaroverflow** [comment]
Good news! It sounds like we were actually working on this in parallel - one of our contractors has a working solution ready for review - so this might happen sooner than expected 😄 

🎉 https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/390

**Comment by kporras07** [comment]
This was finally merged in https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/391 

I'm closing this issue now, feel free to reopen or open a new one if further discussion is needed :)
