### ISSUE TITLE
Git command fails on Windows

### ISSUE THREAD

**Issue by keithdoyle9** [pantheon-systems/terminus-build-tools-plugin#360]
`[notice] Running git -C C:\Users\Keith\AppData\Local\Temp\locDC2A.tmp/seic-test-site commit -m 'Create new Pantheon site from pantheon-systems/example-drops-8-composer'
error: pathspec 'new' did not match any file(s) known to git
error: pathspec 'Pantheon' did not match any file(s) known to git
error: pathspec 'site' did not match any file(s) known to git
error: pathspec 'from' did not match any file(s) known to git
error: pathspec 'pantheon-systems/example-drops-8-composer'' did not match any file(s) known to git
 [CompletionWrapper]  Command `git -C C:\Users\Keith\AppData\Local\Temp\locDC2A.tmp/seic-test-site commit -m 'Create new Pantheon site from pantheon-systems/example-drops-8-composer'` failed with exit code 1
 [CompletionWrapper]  Exit code 1`

Running the command separately after the failure with double quotes runs successfully. Not sure if it's possible to refactor the passthru command to work regardless of environment. Other passthru commands seem to work fine with single quotes. This was run in Cmder on Windows 10.

**Comment by greg-1-anderson** [comment]
Windows is not supported by the Terminus Build Tools plugin or Terminus. There are no technical reasons why it could not be supported; it is just a matter of testing.

In theory, we could consider pull requests that fix quoting. In practice, though, we recommend Windows users run under a VM.

**Comment by keithdoyle9** [comment]
@greg-1-anderson Thanks. Started running commands in WSL and all is well.
