### ISSUE TITLE
Account for Drupal 9 in project create command

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#368]
[`expandSourceAliases`](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/de2d8c0f06fb1705efa8f1c54ea98eb8dbc02610/src/Commands/BuildToolsBase.php#L323
) and [`autodetectUpstreamAtDir`](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/de2d8c0f06fb1705efa8f1c54ea98eb8dbc02610/src/Commands/BuildToolsBase.php#L364) have logic to account for different versions of Drupal. I'd like to see support for Drupal 9 in here.

There's probably a need for a bigger conversation with @greg-1-anderson @sugaroverflow @ari-gold and @joshkoenig around how Build Tools and Integrated Composer should intersect. IMO, anyone using Build Tools probably does not want to use Integrated Composer (because I think any value added by Integrated Composer functionality will be undermined by the confusion of moving `composer.lock` changes in two directions, from Pantheon to GitHub and from GitHub to Pantheon.)

This task is a blocker for https://github.com/pantheon-systems/drupal-9-with-circleci-orb/issues/6

**Comment by greg-1-anderson** [comment]
I am undecided about build tools with Integrated Composer; I am leaning towards saying that does make sense, since the repository contents are the same with integrated Composer, so pushback becomes much simpler.

I am still +1 on using Build Tools without Integrated Composer, though, and it is fine to keep working around the MariaDB issue with patches for now as long as folks are aware of the risk / unsupported disposition of this configuration. We won't be able to move forward here with general support for Drupal 9 without patches (with or without Integrated Composer) until Drupal 9 reaches General Availability on Pantheon.

**Comment by rvtraveller** [comment]
My general thought was that we would offer build tools with a flag of some sort to opt in to an Integrated Composer setup (I'm thinking current process would be the default). I'm guessing there are some people who want certain pieces of Build Tools (like automated testing through CI) but want functionality that is more common through the dashboard -- such as 1 click upstream updates.

Or, another scenario -- agency that builds a site for a client that is then being taken over by the client's IT team for development and said IT team doesn't have a need/desire/ability to use a third party Git provider.

**Comment by greg-1-anderson** [comment]
Just an update on my opinions. It seems like it will be a while before we have external CI with Integrated Composer, and furthermore, Integrated Composer works much better than traditional Build Tools vis-a-vis custom upstreams, so I am strongly in favor of Build Tools + Integrated Composer, to provide CI + generated assets in a custom-upstream-friendly way.

To do this for Drupal 9, we need either a new empty upstream with the databases field set in pantheon.upstream.yml, or we need to wait for support for upgrading to MariaDB on existing sites.

**Comment by kporras07** [comment]
This was added recently in https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/396 so I think this can be closed now. Feel free to reopen if further discussion is needed
