### ISSUE TITLE
Rename Default Branch From Master to Main 

### ISSUE THREAD

**Issue by aweingarten** [pantheon-systems/terminus-build-tools-plugin#381]
GitHub has changed the default branch naming convention from `master` to `main` 
https://github.com/github/renaming 

See: 
https://sfconservancy.org/news/2020/jun/23/gitbranchname/

Terminus build tools should follow github's example for new projects

**Comment by sugaroverflow** [comment]
Linking related issue to check on some previous blockers to this https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/347

**Comment by greg-1-anderson** [comment]
We could perhaps support a different default branch name for external repositories e.g. on GitHub, but for the time being we would still need to push that branch to the `master` branch on Pantheon when deploying merged pull requests, for the reasons mentioned in the issue linked above.

**Comment by sugaroverflow** [comment]
Thank you @greg-1-anderson ! :) 

@aweingarten if you were referring to something else, please let me know - otherwise this can't be fixed at the moment (we'll have to wait for platform changes). Thank you!
