### ISSUE TITLE
Feature request: make cron schedule configurable (for non-circle providers)

### ISSUE THREAD

**Issue by aaronbauman** [pantheon-systems/terminus-build-tools-plugin#394]
As a project admin, I want to reduce the amount of CI time spent running automated composer update checks, so that I can reduce my bills. Bitbucket pipelines charges ($) for CI usage, and I don't need all my projects running composer lock update (clu) checks every night.

BitbucketPipelinesProvider::startTesting and GitLabCIProvider::startTesting methods use a hard-coded string to set the cron schedule. (Circle CI provider specifies the schedule in yaml.)

It would be useful if the cron schedule could be specified upon project creation, e.g. from a command line argument.

**Comment by greg-1-anderson** [comment]
Tracking as CMS-231
