### ISSUE TITLE
Gitlab Tokens are Broken

### ISSUE THREAD

**Issue by jet082** [pantheon-systems/terminus-build-tools-plugin#426]
Gitlab access tokens can include - and _, but this is not accepted in the input for access tokens.

**Comment by kporras07** [comment]
Hi,
Thanks for reporting. Working on this in #427

**Comment by kporras07** [comment]
Thanks for reporting. This has been included in 3.0.1 release. Closing this ticket. Feel free open a new ticket if you have further questions/issues
