### ISSUE TITLE
Spinning up Pantheon/GitHub/CircleCI site with terminus build tools causes fatal error for d9

### ISSUE THREAD

**Issue by junkgamestuff** [pantheon-systems/terminus-build-tools-plugin#446]
When trying to spin up a Pantheon/GitHub/CircleCI site using terminus build tools, I get the following error:

Cloning into '.'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 [error]  Command `git -C /private/var/folders/lr/ylr8n0c51g32brwnkn5yvhhw0000gn/T/template-dir0NkaJl clone git@github.com:pantheon-upstreams/drupal-recommended.git --depth 1 .` failed with exit code 128 

This only happens with d9. I am able to set up a d8 or a wordpress site using terminus build tools without a problem.

I am currently using terminus version 3.0.7

**Comment by kporras07** [comment]
@junkgamestuff that's weird. What happens if you try to clone pantheon-upstreams/drupal-recommended?

`git clone git@github.com:pantheon-upstreams/drupal-recommended.git` does it work?

**Comment by mjuarez2** [comment]
I can clone the repo without any problem.

**Comment by junkgamestuff** [comment]
I tried to clone the repo and this is the result:

Cloning into 'drupal-recommended'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by junkgamestuff** [comment]
I see now that I didn't have my SSH key set up in GitHub. Once I added that, I was able to gain access to the repo.
