### ISSUE TITLE
terminus build:project:create fails with PHP fatal error

### ISSUE THREAD

**Issue by cornifex** [pantheon-systems/terminus-build-tools-plugin#456]
Running `terminus build:project:create --ci=githubactions wp my-test-site` fails with:
```
PHP Fatal error:  Uncaught Error: Call to a member function application() on bool in /home/me/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/ProjectCreateCommand.php:341
```

- Terminus version: 3.0.7
- Build tools version: 3.0.2
- PHP version: 8.1.7
- OS: Linux/Ubuntu (PopOS 20.04)

**Comment by kporras07** [comment]
Hi @cornifex thanks for reporting this issue.

I just tagged a new release on the template repository so this command should work now as expected. 

Feel free to reopen/open a new issue if you keep having issues with Build Tools.
