### ISSUE TITLE
Build tools not accepting CircleCI personal API token

### ISSUE THREAD

**Issue by rbomhof** [pantheon-systems/terminus-build-tools-plugin#482]
We are trying to use build tools to create a new D10 site, and the script keeps prompting us with the following after entering our token (which contains an underscore):

`Circle CI authentication tokens should be 40-character strings containing only the letters a-f and digits (0-9). Please enter your token again.`

**Comment by kporras07** [comment]
Hi @rbomhof this was included in a new release of the plugin. Please update your plugin installation and give it another try
