### ISSUE TITLE
install workflow

### ISSUE THREAD

**Issue by jraviotta** [pantheon-systems/terminus-build-tools-plugin#49]
I'm not a fan of the plugin installation workflow. Installation in $HOME/.terminus adds a local dependency that is a barrier to onboarding devs with a single composer.json manifest. I would prefer to add the plugins as I add terminus itself with a `composer require` command so that `composer install` takes care of the installation.

**Comment by greg-1-anderson** [comment]
Moved this request to https://github.com/pantheon-systems/terminus/issues/1728
