### ISSUE TITLE
Handling of a non-master default branch

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#58]
Hi @greg-1-anderson, I was working with @haynescw to set up a Drupal 8 + Travis repo. In his repo, the default branch is not `master` but `develop`. Should this plugin support configuration where a branch other than `master` on GitHub lines up with the Pantheon `master` branch?

The troublespot is the merge command where it is assumed that the github repo branch to be checked out is master: https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Commands/EnvMergeCommand.php#L65

**Comment by greg-1-anderson** [comment]
Yes, this is a reasonable thing to do. If you check out the `develop` branch on [65](https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Commands/EnvMergeCommand.php#L65), you'd just need to push `develop:master` a couple of lines later.

**Comment by greg-1-anderson** [comment]
Does `build:env:create` do the right thing?

**Comment by stevector** [comment]
@haynescw, can you confirm that `build:env:create` does the right thing. I think it does.

Also I tried something slightly different here: https://github.com/pantheon-systems/terminus-build-tools-plugin/commit/4ae58817b454f16646e48a249ad640ddb9f0bf55 It might be better to just check out Pantheon's master branch. If the idea is to merge a Multidev on Pantheon to Pantheon's `master` then let's do that directly rather than using `master` from the source repo.

I made this change in the 1.x branch because that is what @haynescw is using.

**Comment by haynescw** [comment]
Yes, build:env:create seems to do the right thing. It creates a multitdev to be merged into the dev env like it should based on the current travis build id.

**Comment by stevector** [comment]
Closed via https://github.com/pantheon-systems/terminus-build-tools-plugin/issues/61
