### ISSUE TITLE
Cleanup repos in pantheon-ci-bot

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/terminus-build-tools-plugin#65]
That bot is up to 204 repos

https://github.com/pantheon-ci-bot?tab=repositories

Our build script should probably prune all by the newest N repos. 10? 20? @greg-1-anderson, what do you think?

**Comment by greg-1-anderson** [comment]
The build script is currently removing each repo as it finishes. For some reason, this isn't working at the moment, so the repos are building up.

**Comment by stevector** [comment]
@greg-1-anderson, I see the bot is now down to 23 repos. Did this cleanup get automated?

**Comment by greg-1-anderson** [comment]
Yeah, I think this is working again.

**Comment by stevector** [comment]
K, can we close this issue?

**Comment by greg-1-anderson** [comment]
Yeah, I just double-checked, and there have been no orphaned repositories since the handful that piled up while I was fixing this. I'll delete those by hand later, and close this.
