### ISSUE TITLE
build-env:create-project fails for d7

### ISSUE THREAD

**Issue by jraviotta** [pantheon-systems/terminus-build-tools-plugin#70]
[InvalidArgumentException]
  Could not find package pantheon-systems/example-drops-7-composer with stability stable.

**Comment by greg-1-anderson** [comment]
There is no stable tag for example-drops-7-composer because Drupal 7 is not supported with this tool yet. Sorry the documentation is not clear on this point.

This should be available shortly, though.

**Comment by greg-1-anderson** [comment]
We have an alpha tag for the d7 repository, so you can now try out Drupal 7 via:
```
terminus build:project:create d7 my-awesome-d7-site --stability=alpha
```
Be sure to use the `master` branch of the Terminus Build Tools Plugin.

**Comment by ataylorme** [comment]
Cleaning up old issues. @jraviotta if you have issues in the latest version of build tools please re-open
