### ISSUE TITLE
build:project:create --git=bitbucket fails with CircleCI API error

### ISSUE THREAD

**Issue by LukasRos** [pantheon-systems/terminus-build-tools-plugin#86]
The _POST …/envvar_ call going to the CircleCI API fails for Bitbucket projects and returns “Permission denied”.

Testing showed that any write request to the CircleCI API for a new Bitbucket project or even build webhook calls fail; Circle only accepts the Bitbucket project when it’s created or opened at least once through the website UI, there’s no way to programmatically enable a new project in Circle.

This breaks the workflow implemented in the build tools; the same workflow that's working with Github projects on Circle.

**Comment by greg-1-anderson** [comment]
From slack conversation:
> ... simply opening the project’s URL which automatically creates it.
> ... then everything in the API works fine.

**Comment by ataylorme** [comment]
@greg-1-anderson I used build tools to create a site with BitBucket this morning. My first attempt failed, as @LukasRos suggested. I then authorized BitBucket from CircleCI and tried again with success.

Though my error wasn't explicitly permission denied (actual error below) it seems to have been a permission issue. I expect GitHub creation would fail as well if CircleCI hasn't been authorized with GitHub. I think we document this but can reasonably ask users to authorize GItHub/BitBucket with CircleCI before running build tools (they are already logging into CircleCI to create an authorization token).

CircleCI Error:
> Server error: `POST https://circleci.com/api/v1.1/project/bitbucket/ataylorme/caldera-forms/envvar` resulted in a `500 Internal Server Error`

**Comment by greg-1-anderson** [comment]
Question: if you authenticate with BitBucket, and then succeed, and then you create a second project on BitBucket, is a separate authentication needed for the second project, or does it succeed without any further need for interactivity?

If browser authentication is only required once, then I think we can say this behaves correctly.

**Comment by LukasRos** [comment]
As per my tests authentication with Bitbucket in CircleCI is only required once but adding a second project also requires going to the Bitbucket UI to open that project before running build tools.

**Comment by greg-1-anderson** [comment]
Let's see if BitBucket with the BitBucket test framework works better. I don't see a lot of demand for BitBucket + CircleCI; it seems that BitBucket + Jenkins has the most requests.

**Comment by ataylorme** [comment]
Cleaning up old issues. Closing this out as a duplicate of proper BitBucket support (#145).
