### ISSUE TITLE
terminus build-env:delete:ci deletes non ci-build environments 

### ISSUE THREAD

**Issue by greg-1-anderson** [pantheon-systems/terminus-build-tools-plugin#87]
See:

https://github.com/pantheon-systems/terminus/issues/1745

**Comment by greg-1-anderson** [comment]
See: https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/88

**Comment by greg-1-anderson** [comment]
Fixed on `master` branch.

**Comment by greg-1-anderson** [comment]
Backported to 1.x: https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/89

**Comment by stevector** [comment]
@greg-1-anderson Can this issue be closed?

**Comment by greg-1-anderson** [comment]
Yes, thanks.
